# Personnel Expectations {.tabset}

## PI
* I am responsible for the overall lab vision and direction. This mainly includes developing project ideas and obtaining lab funding. But on a daily basis, it also means I am responsible for ensuring the lab produces research products.
* I am responsible for contributing to the professional development of all lab members. I will try to prioritize this depending on the goals of each individual, but the better we can communicate about your goals, the more successful I will be in this regard.
* I will support your general education in psychology, broader education in related fields, and specific education in the cognitive neuroscience of spatial navigation.
* I will contribute to all ongoing projects in the form of: commenting on written drafts, presentations, and posters; helping develop and troubleshoot analyses; ensuring all resources needed for a project are available; providing opportunities for networking, collaboration, and professional development; designing and implementing experiments and protocols; helping manage the lab infrastructure (including analysis pipelines, data backup, and data storage).
* I will support the physical and mental health and safety of everyone in the lab.

## PhD Students
In general PhD students have a fairly loose leash as long as they are making progress on projects. In practice, this likely means there will be crunch times where you're working hard to get things done, and lighter times when you can take it easy. Please let the PI know, though, if you plan to take extended time off (more than a few days).

PhD students are expected to:

* Develop and manage an independent project.

* Know the literature and learn the skills related to their project.

* Have a strong grasp of (nearly all aspects of) cognitive neuroscience; a breadth of knowledge from areas closely related (psychology, mostly); and a familiarity with related disciplines (biology, anthropology, philosophy, etc.)

* Grow skills in writing, data analysis, experiment administration and protocols, and presentation.

* Generate (ideally and roughly) one research product per year in the lab.

* Seek out opportunities for awards (fellowships, travel awards)

* Advocate for what they think and what they need to do their jobs

* Develop (or maintain) healthy work habits and a good balance.

## Lab Manager
The lab manager will have a regular schedule to ensure a stability in the lab. Due to the nature of OPS positions at UF, 8 hours per day is expected, and these hours should occur roughly between 8am and 6pm. There will be exceptions to this - weekend or late night fMRI scanning sessions come to mind - and these hours can be 'made up for' during the week. Time off requests can be somewhat informal, but should be submitted to the PI in writing so we have a record of such things.

The Lab Manager is expected to:

* Facilitate lab business, including:

  * Recruiting participants

  * Organizing and documenting data storage and backups

  * Updating the lab website and Twitter

* Facilitate projects, including:

  * Managing human subject payments

  * IRB protocol updates

  * Putting projects online (via Prolific, M-Turk, Pavlovia, etc.)

  * Running experiments
  
  * Soliciting (from lab members) submitting purchase requests

* Contribute to their own project (this will depend on the particular person, but all lab managers will have the opportunity to work on their own research project(s)).

* Develop and maintain code, including:

  * Lab github

  * Lab Hipergator account(s)

  * Virtual Silcton

* Develop and maintain documentation, including:

  * Lab experimental and consent protocols

  * fMRI administration checklists

  * Virtual Silcton website administration protocols

  * fMRI pipelines and data analysis

## Undergraduate RAs (PSY4911)
Undergraduate research assistants help with research duties. But, especially if this is your first time working in a research lab, you should not just blindly go about your work and do what you're told. Look for ways you can actively contribute to the lab. This includes generating your own ideas, but also developing your own skills. You should not have empty time in the lab, but rather pick a skill you're interested in learning (consult with your grad mentor or Dr. Weisberg if necessary), and spend your free lab time teaching yourself.

Undergraduate research assistants are expected to:

* Work in the lab 3-hours per credit per week; the general minimum is 9-hours per week (though the number of credits can be less than 3)

* Contribute to a project, including:

  * Recruiting participants

  * Running participants

  * Developing a project (collecting stimuli, coding the study)

  * Coding data

  * Analyzing data (to some extent)

* Develop their own skills, including:

  * Knowledge of fMRI

  * Ability to code in Python, R, Matlab, and C# (Unity3D).

  * Knowledge of the literature of cognitive neuroscience as pertains to their projects.

## Undergraduate Honors Students (PSY 4970)
Undergraduate research assistants who have worked in the lab for at least one year will have the opportunity to propose an Honors thesis. 

A typical Honor's thesis will be a relatively small-scale project that is easy to design, collect data for, and analyze. A strong Honor's thesis will have clear hypotheses and pre-registered methods and analysis. The Honor's thesis will be undertaken primarily by the student, under the supervision of a lab member (usually grad student or post-doc). The writing and presentation must be done primarily by the student. 

Here are the requirements (adapted from this [website](https://psych.ufl.edu/undergrad/research-internship-teaching-experiences/research-experience/)):

- (At least) 1 year prior to defending: 
  - Schedule a meeting with Steve to discuss the possibility of an Honor's thesis and to develop a topic and a direct advisor (either Steve or, more likely, a graduate student or post-doc in the lab).
  - Create a list of at least 5-10 highly relevant papers you will read and provide an annotated bibliography to Dr. Weisberg. These papers should be mostly empirical, and approved by Dr. Weisberg (or your direct advisor). They should be coherent around a topic which you want to focus on. 
  - Schedule a presentation in lab meeting to propose the rough outline of your project and the literature review you conducted. 
- In the semester *before* you defend: 
  - Select members for your thesis committee (Steve and two other faculty members, typically though not always in the Psychology department) 
  - Develop a 7-pg double-spaced written proposal
  - Fill out the [registration form](https://psych.ufl.edu/wp-content/uploads/sites/75/PSY-4970_2020.pdf). If out of date, check the [website](https://psych.ufl.edu/undergrad/research-internship-teaching-experiences/research-experience/).
  - Submit the registration form to the Psychology Advising Office (Room PSY 135). 
- In the semester you defend: 
  - Schedule the thesis defense. This must be **prior** to the last day of classes, but as a rule, it should be at least two weeks before to allow time for rescheduling if necessary. 
  - Reserve a room (usually PSY 108) by emailing the [dedicated staff person](https://psych.ufl.edu/directory/staff/)
  - Complete the project, analyze the data, write the full thesis. 
  - Schedule a lab meeting for a practice presentation and to get feedback on the results / analyses. 
  - Submit the thesis for Dr. Weisberg to review and give feedback **at least one week before the defense**.
  - Create a 15-minute presentation outlining the Introduction (background, motivation, and hypotheses), Method (participants, materials, experiment structure, measures), Results (analyses and outcomes), and Discussion (interpretation, limitations, and next steps). 
  - Send the thesis to all committee members (including Dr. Weisberg and your direct advisor) at least one week prior to the defense. Include in your email a reminder of the date/time and room of the defense. 
- On the day of the defense (which must be prior to the last day of classes): 
  - Make sure you have your presentation and a copy of your thesis on a flash drive and online somewhere (e.g., Dropbox, Onedrive, or emailed to yourself). 
  - Arrive at least 10 minutes early to set up any equipment. 
  - Bring with you a copy of [this form](https://psych.ufl.edu/wp-content/uploads/sites/75/defense_form.pdf) to be signed after the defense. 
- After the defense: 
  - Submit the defense form to Psych advising in PSY 135. 
  - [Follow the instructions on submitting your thesis electronically](http://cms.uflib.ufl.edu/etd/honors#Submit). 
  - CELEBRATE! 