# Onboarding checklist {#onboarding}

*Welcome to the SCANN Lab! Below you will find information and a checklist on getting started in lab. If you have any questions, please reach out to the lab manager.*

## Steps to follow:

1. Email the lab manager with subject line "New SCANN Lab Member". The lab manager email can be found [here](https://scannlab.psych.ufl.edu/lab-manager/).
2. The lab manager will email you back with information on how to join our Slack channel, when our meetings will be, and how to finish onboarding.
3. Make sure you finish the following tasks for onboarding:

  - [ ] You are added to the Slack channel
  - [ ] You are added to the Google Drive
  - [ ] You finish your website update and send all information to the lab manager and Dr. Weisberg for approval.
  - [ ] You are added to the necessary IRB studies
  - [ ] You finish all relevant tasks on Trello
  - [ ] You finish all relevant trainings through [myUFL](https://my.ufl.edu/ps/signon.html)
  - [ ] You are given a tour of lab space and where you will be conducting research.
  - [ ] You are given building access to any areas you need to access.
